version: '3.1'

networks:
  proxynet:
    name: near-bye-network

services:
  near-bye-bff:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
      - rsa-keys-dev/public.test.pem.env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - proxynet
