version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: